sudo: required
services:
  - docker

before_install:
  - docker build -t himanshuteotia/docker-react -f Dockerfile.dev .

script:
  - docker run himanshuteotia/docker-react npm run test -- --coverage
